// comment
pipeline {
 agent any
 stages {
        stage('Checkout-git'){
               steps{
                echo 'Revisando repositorio del Proyecto'
		git poll: true, url: 'https://github.com/kaizenportal/kaizen-web.git'
               }
        }
        stage('Build Project') {
            steps {
                echo 'Realizando Build al Proyecto'
		bat 'C:\\maven-3.6.2\\bin\\mvn clean compile package'

            }
        }
        /*stage('Test Project') {
            steps {
                echo 'Realizando Test al Proyecto'
		bat 'C:\\maven-3.6.2\\bin\\mvn verify'

            }
        }*/
        stage('SonarQube Project') {
            steps {
                echo 'Test SonarQube'
		bat 'C:\\maven-3.6.2\\bin\\mvn sonar:sonar -Dsonar.projectKey=integracion-continua -Dsonar.host.url=http://10.0.11.15:9000 -Dsonar.login=e799fc83980ef097d519d379b6290ab17f6f29aa'

            }
        }
        /*stage('Deploy Artifactory') {
            steps {
                echo 'Desplegando artefacto en nexus'
		bat 'C:\\maven-3.6.2\\bin\\mvn deploy'

            }
        }*/
        /*stage('CreateVirtualEnv') {
            steps {
				sh '''
					bash -c "virtualenv entorno_virtual && source entorno_virtual/bin/activate"
				'''

            }
        }
        stage('InstallRequirements') {
            steps {
            	sh '''
            		bash -c "source ${WORKSPACE}/entorno_virtual/bin/activate && ${WORKSPACE}/entorno_virtual/bin/python ${WORKSPACE}/entorno_virtual/bin/pip install -r requirements.txt"
                '''
            }
        }   
        stage('TestApp') {
            steps {
            	sh '''
            		bash -c "source ${WORKSPACE}/entorno_virtual/bin/activate &&  cd src && ${WORKSPACE}/entorno_virtual/bin/python ${WORKSPACE}/entorno_virtual/bin/pytest && cd .."
                '''
            }
        }  
        stage('RunApp') {
            steps {
            	sh '''
            		bash -c "source entorno_virtual/bin/activate ; ${WORKSPACE}/entorno_virtual/bin/python src/main.py &"
                '''
            }
        } 
        stage('BuildDocker') {
            steps {
            	sh '''
            		docker build -t apptest:latest .
                '''
            }
        } 
    stage('PushDockerImage') {
            steps {
            	sh '''
            		docker tag apptest:latest mijack/apptest:latest
					docker push mijack/apptest:latest
					docker rmi apptest:latest
                '''
            }
        }*/ 
  }
}

